/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false` (hash: 15dd420dfccac8afafeb181790b9eddb)
declare namespace Cloudflare {
	interface Env {
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
	}
}
interface Env extends Cloudflare.Env {}
